// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/protocol/proto/group.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 群组信息
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerUid      string                 `protobuf:"bytes,4,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`
	MemberUids    []string               `protobuf:"bytes,5,rep,name=member_uids,json=memberUids,proto3" json:"member_uids,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Remark        string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"` // 当前用户在该群的备注（每个人都不同）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetOwnerUid() string {
	if x != nil {
		return x.OwnerUid
	}
	return ""
}

func (x *Group) GetMemberUids() []string {
	if x != nil {
		return x.MemberUids
	}
	return nil
}

func (x *Group) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Group) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Group) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 群组成员信息
type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"` // 群内昵称
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`         // owner, admin, member
	JoinTime      int64                  `protobuf:"varint,5,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMember) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GroupMember) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GroupMember) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

// 群聊消息
type GroupMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	FromUid       string                 `protobuf:"bytes,3,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	FromUsername  string                 `protobuf:"bytes,4,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MessageType   string                 `protobuf:"bytes,6,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // text, image, file, emoji
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMessage) Reset() {
	*x = GroupMessage{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessage) ProtoMessage() {}

func (x *GroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessage.ProtoReflect.Descriptor instead.
func (*GroupMessage) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{2}
}

func (x *GroupMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GroupMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMessage) GetFromUid() string {
	if x != nil {
		return x.FromUid
	}
	return ""
}

func (x *GroupMessage) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

func (x *GroupMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *GroupMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 创建群组请求
type CreateGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OwnerUid      string                 `protobuf:"bytes,3,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`
	MemberUids    []string               `protobuf:"bytes,4,rep,name=member_uids,json=memberUids,proto3" json:"member_uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupReq) GetOwnerUid() string {
	if x != nil {
		return x.OwnerUid
	}
	return ""
}

func (x *CreateGroupReq) GetMemberUids() []string {
	if x != nil {
		return x.MemberUids
	}
	return nil
}

// 创建群组响应
type CreateGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResp) Reset() {
	*x = CreateGroupResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResp) ProtoMessage() {}

func (x *CreateGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResp.ProtoReflect.Descriptor instead.
func (*CreateGroupResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateGroupResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateGroupResp) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// 加入群组请求
type JoinGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupReq) Reset() {
	*x = JoinGroupReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupReq) ProtoMessage() {}

func (x *JoinGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupReq.ProtoReflect.Descriptor instead.
func (*JoinGroupReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{5}
}

func (x *JoinGroupReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinGroupReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// 加入群组响应
type JoinGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupResp) Reset() {
	*x = JoinGroupResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResp) ProtoMessage() {}

func (x *JoinGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResp.ProtoReflect.Descriptor instead.
func (*JoinGroupResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{6}
}

func (x *JoinGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JoinGroupResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 退出群组请求
type LeaveGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupReq) Reset() {
	*x = LeaveGroupReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupReq) ProtoMessage() {}

func (x *LeaveGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupReq.ProtoReflect.Descriptor instead.
func (*LeaveGroupReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveGroupReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *LeaveGroupReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// 退出群组响应
type LeaveGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupResp) Reset() {
	*x = LeaveGroupResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupResp) ProtoMessage() {}

func (x *LeaveGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupResp.ProtoReflect.Descriptor instead.
func (*LeaveGroupResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LeaveGroupResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取群组列表请求
type GroupListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListReq) Reset() {
	*x = GroupListReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListReq) ProtoMessage() {}

func (x *GroupListReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListReq.ProtoReflect.Descriptor instead.
func (*GroupListReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{9}
}

func (x *GroupListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// 获取群组列表响应
type GroupListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Groups        []*Group               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListResp) Reset() {
	*x = GroupListResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListResp) ProtoMessage() {}

func (x *GroupListResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListResp.ProtoReflect.Descriptor instead.
func (*GroupListResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{10}
}

func (x *GroupListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GroupListResp) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

// 获取群组成员请求
type GroupMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembersReq) Reset() {
	*x = GroupMembersReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersReq) ProtoMessage() {}

func (x *GroupMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembersReq.ProtoReflect.Descriptor instead.
func (*GroupMembersReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{11}
}

func (x *GroupMembersReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// 获取群组成员响应
type GroupMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Members       []*GroupMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembersResp) Reset() {
	*x = GroupMembersResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersResp) ProtoMessage() {}

func (x *GroupMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembersResp.ProtoReflect.Descriptor instead.
func (*GroupMembersResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{12}
}

func (x *GroupMembersResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupMembersResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GroupMembersResp) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// 获取群组信息请求
type GroupInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoReq) Reset() {
	*x = GroupInfoReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoReq) ProtoMessage() {}

func (x *GroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoReq.ProtoReflect.Descriptor instead.
func (*GroupInfoReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{13}
}

func (x *GroupInfoReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// 获取群组信息响应
type GroupInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Group         *Group                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoResp) Reset() {
	*x = GroupInfoResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoResp) ProtoMessage() {}

func (x *GroupInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoResp.ProtoReflect.Descriptor instead.
func (*GroupInfoResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{14}
}

func (x *GroupInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GroupInfoResp) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

// 发送群聊消息请求
type SendGroupMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	FromUid       string                 `protobuf:"bytes,2,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageReq) Reset() {
	*x = SendGroupMessageReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageReq) ProtoMessage() {}

func (x *SendGroupMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageReq.ProtoReflect.Descriptor instead.
func (*SendGroupMessageReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{15}
}

func (x *SendGroupMessageReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SendGroupMessageReq) GetFromUid() string {
	if x != nil {
		return x.FromUid
	}
	return ""
}

func (x *SendGroupMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendGroupMessageReq) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

// 发送群聊消息响应
type SendGroupMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageResp) Reset() {
	*x = SendGroupMessageResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageResp) ProtoMessage() {}

func (x *SendGroupMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageResp.ProtoReflect.Descriptor instead.
func (*SendGroupMessageResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{16}
}

func (x *SendGroupMessageResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendGroupMessageResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendGroupMessageResp) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// 获取群聊消息历史请求
type GroupMessageHistoryReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeTimestamp int64                  `protobuf:"varint,3,opt,name=before_timestamp,json=beforeTimestamp,proto3" json:"before_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupMessageHistoryReq) Reset() {
	*x = GroupMessageHistoryReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessageHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessageHistoryReq) ProtoMessage() {}

func (x *GroupMessageHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessageHistoryReq.ProtoReflect.Descriptor instead.
func (*GroupMessageHistoryReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{17}
}

func (x *GroupMessageHistoryReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMessageHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GroupMessageHistoryReq) GetBeforeTimestamp() int64 {
	if x != nil {
		return x.BeforeTimestamp
	}
	return 0
}

// 获取群聊消息历史响应
type GroupMessageHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Messages      []*GroupMessage        `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMessageHistoryResp) Reset() {
	*x = GroupMessageHistoryResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessageHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessageHistoryResp) ProtoMessage() {}

func (x *GroupMessageHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessageHistoryResp.ProtoReflect.Descriptor instead.
func (*GroupMessageHistoryResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{18}
}

func (x *GroupMessageHistoryResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupMessageHistoryResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GroupMessageHistoryResp) GetMessages() []*GroupMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 邀请好友入群请求
type InviteToGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	InviterUid    string                 `protobuf:"bytes,2,opt,name=inviter_uid,json=inviterUid,proto3" json:"inviter_uid,omitempty"`
	InviteeUids   []string               `protobuf:"bytes,3,rep,name=invitee_uids,json=inviteeUids,proto3" json:"invitee_uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteToGroupReq) Reset() {
	*x = InviteToGroupReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteToGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteToGroupReq) ProtoMessage() {}

func (x *InviteToGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteToGroupReq.ProtoReflect.Descriptor instead.
func (*InviteToGroupReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{19}
}

func (x *InviteToGroupReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *InviteToGroupReq) GetInviterUid() string {
	if x != nil {
		return x.InviterUid
	}
	return ""
}

func (x *InviteToGroupReq) GetInviteeUids() []string {
	if x != nil {
		return x.InviteeUids
	}
	return nil
}

// 邀请好友入群响应
type InviteToGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteToGroupResp) Reset() {
	*x = InviteToGroupResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteToGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteToGroupResp) ProtoMessage() {}

func (x *InviteToGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteToGroupResp.ProtoReflect.Descriptor instead.
func (*InviteToGroupResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{20}
}

func (x *InviteToGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InviteToGroupResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 踢出群成员请求
type KickFromGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   string                 `protobuf:"bytes,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"`
	TargetUid     string                 `protobuf:"bytes,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickFromGroupReq) Reset() {
	*x = KickFromGroupReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickFromGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickFromGroupReq) ProtoMessage() {}

func (x *KickFromGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickFromGroupReq.ProtoReflect.Descriptor instead.
func (*KickFromGroupReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{21}
}

func (x *KickFromGroupReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *KickFromGroupReq) GetOperatorUid() string {
	if x != nil {
		return x.OperatorUid
	}
	return ""
}

func (x *KickFromGroupReq) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

// 踢出群成员响应
type KickFromGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickFromGroupResp) Reset() {
	*x = KickFromGroupResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickFromGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickFromGroupResp) ProtoMessage() {}

func (x *KickFromGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickFromGroupResp.ProtoReflect.Descriptor instead.
func (*KickFromGroupResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{22}
}

func (x *KickFromGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *KickFromGroupResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 设置群内昵称请求
type SetGroupNicknameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupNicknameReq) Reset() {
	*x = SetGroupNicknameReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupNicknameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupNicknameReq) ProtoMessage() {}

func (x *SetGroupNicknameReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupNicknameReq.ProtoReflect.Descriptor instead.
func (*SetGroupNicknameReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{23}
}

func (x *SetGroupNicknameReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetGroupNicknameReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SetGroupNicknameReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// 设置群内昵称响应
type SetGroupNicknameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupNicknameResp) Reset() {
	*x = SetGroupNicknameResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupNicknameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupNicknameResp) ProtoMessage() {}

func (x *SetGroupNicknameResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupNicknameResp.ProtoReflect.Descriptor instead.
func (*SetGroupNicknameResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{24}
}

func (x *SetGroupNicknameResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetGroupNicknameResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 新增：修改群名请求
type UpdateGroupNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   string                 `protobuf:"bytes,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupNameReq) Reset() {
	*x = UpdateGroupNameReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupNameReq) ProtoMessage() {}

func (x *UpdateGroupNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupNameReq.ProtoReflect.Descriptor instead.
func (*UpdateGroupNameReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateGroupNameReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupNameReq) GetOperatorUid() string {
	if x != nil {
		return x.OperatorUid
	}
	return ""
}

func (x *UpdateGroupNameReq) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type UpdateGroupNameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupNameResp) Reset() {
	*x = UpdateGroupNameResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupNameResp) ProtoMessage() {}

func (x *UpdateGroupNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupNameResp.ProtoReflect.Descriptor instead.
func (*UpdateGroupNameResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateGroupNameResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateGroupNameResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 新增：设置群备注请求
type SetGroupRemarkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupRemarkReq) Reset() {
	*x = SetGroupRemarkReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupRemarkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupRemarkReq) ProtoMessage() {}

func (x *SetGroupRemarkReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupRemarkReq.ProtoReflect.Descriptor instead.
func (*SetGroupRemarkReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{27}
}

func (x *SetGroupRemarkReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetGroupRemarkReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SetGroupRemarkReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type SetGroupRemarkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupRemarkResp) Reset() {
	*x = SetGroupRemarkResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupRemarkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupRemarkResp) ProtoMessage() {}

func (x *SetGroupRemarkResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupRemarkResp.ProtoReflect.Descriptor instead.
func (*SetGroupRemarkResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{28}
}

func (x *SetGroupRemarkResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetGroupRemarkResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 新增：设置群免打扰请求
type SetGroupDNDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Dnd           bool                   `protobuf:"varint,3,opt,name=dnd,proto3" json:"dnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupDNDReq) Reset() {
	*x = SetGroupDNDReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupDNDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupDNDReq) ProtoMessage() {}

func (x *SetGroupDNDReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupDNDReq.ProtoReflect.Descriptor instead.
func (*SetGroupDNDReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{29}
}

func (x *SetGroupDNDReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetGroupDNDReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SetGroupDNDReq) GetDnd() bool {
	if x != nil {
		return x.Dnd
	}
	return false
}

type SetGroupDNDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupDNDResp) Reset() {
	*x = SetGroupDNDResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupDNDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupDNDResp) ProtoMessage() {}

func (x *SetGroupDNDResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupDNDResp.ProtoReflect.Descriptor instead.
func (*SetGroupDNDResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{30}
}

func (x *SetGroupDNDResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetGroupDNDResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 新增：设置/取消禁言请求
type SetGroupMuteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   string                 `protobuf:"bytes,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"`
	TargetUid     string                 `protobuf:"bytes,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Mute          bool                   `protobuf:"varint,4,opt,name=mute,proto3" json:"mute,omitempty"` // true为禁言, false为取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupMuteReq) Reset() {
	*x = SetGroupMuteReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupMuteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupMuteReq) ProtoMessage() {}

func (x *SetGroupMuteReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupMuteReq.ProtoReflect.Descriptor instead.
func (*SetGroupMuteReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{31}
}

func (x *SetGroupMuteReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetGroupMuteReq) GetOperatorUid() string {
	if x != nil {
		return x.OperatorUid
	}
	return ""
}

func (x *SetGroupMuteReq) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

func (x *SetGroupMuteReq) GetMute() bool {
	if x != nil {
		return x.Mute
	}
	return false
}

type SetGroupMuteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupMuteResp) Reset() {
	*x = SetGroupMuteResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupMuteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupMuteResp) ProtoMessage() {}

func (x *SetGroupMuteResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupMuteResp.ProtoReflect.Descriptor instead.
func (*SetGroupMuteResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{32}
}

func (x *SetGroupMuteResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetGroupMuteResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 设置/取消管理员请求
type SetGroupAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   string                 `protobuf:"bytes,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"`
	TargetUid     string                 `protobuf:"bytes,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	SetAdmin      bool                   `protobuf:"varint,4,opt,name=set_admin,json=setAdmin,proto3" json:"set_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupAdminReq) Reset() {
	*x = SetGroupAdminReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupAdminReq) ProtoMessage() {}

func (x *SetGroupAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupAdminReq.ProtoReflect.Descriptor instead.
func (*SetGroupAdminReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{33}
}

func (x *SetGroupAdminReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetGroupAdminReq) GetOperatorUid() string {
	if x != nil {
		return x.OperatorUid
	}
	return ""
}

func (x *SetGroupAdminReq) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

func (x *SetGroupAdminReq) GetSetAdmin() bool {
	if x != nil {
		return x.SetAdmin
	}
	return false
}

// 新增：设置/取消管理员响应
type SetGroupAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupAdminResp) Reset() {
	*x = SetGroupAdminResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupAdminResp) ProtoMessage() {}

func (x *SetGroupAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupAdminResp.ProtoReflect.Descriptor instead.
func (*SetGroupAdminResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{34}
}

func (x *SetGroupAdminResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetGroupAdminResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 新增：解散群组请求
type DismissGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUid   string                 `protobuf:"bytes,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupReq) Reset() {
	*x = DismissGroupReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupReq) ProtoMessage() {}

func (x *DismissGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupReq.ProtoReflect.Descriptor instead.
func (*DismissGroupReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{35}
}

func (x *DismissGroupReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *DismissGroupReq) GetOperatorUid() string {
	if x != nil {
		return x.OperatorUid
	}
	return ""
}

// 新增：解散群组响应
type DismissGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupResp) Reset() {
	*x = DismissGroupResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupResp) ProtoMessage() {}

func (x *DismissGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupResp.ProtoReflect.Descriptor instead.
func (*DismissGroupResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{36}
}

func (x *DismissGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DismissGroupResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取群组成员角色请求
type GroupMemberRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberRoleReq) Reset() {
	*x = GroupMemberRoleReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberRoleReq) ProtoMessage() {}

func (x *GroupMemberRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberRoleReq.ProtoReflect.Descriptor instead.
func (*GroupMemberRoleReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{37}
}

func (x *GroupMemberRoleReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMemberRoleReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// 获取群组成员角色响应
type GroupMemberRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // owner, admin, member
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberRoleResp) Reset() {
	*x = GroupMemberRoleResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberRoleResp) ProtoMessage() {}

func (x *GroupMemberRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberRoleResp.ProtoReflect.Descriptor instead.
func (*GroupMemberRoleResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{38}
}

func (x *GroupMemberRoleResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupMemberRoleResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GroupMemberRoleResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// 获取群组成员信息请求
type GroupMemberInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberInfoReq) Reset() {
	*x = GroupMemberInfoReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberInfoReq) ProtoMessage() {}

func (x *GroupMemberInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberInfoReq.ProtoReflect.Descriptor instead.
func (*GroupMemberInfoReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{39}
}

func (x *GroupMemberInfoReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMemberInfoReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// 获取群组成员信息响应
type GroupMemberInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	JoinTime      int64                  `protobuf:"varint,7,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberInfoResp) Reset() {
	*x = GroupMemberInfoResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberInfoResp) ProtoMessage() {}

func (x *GroupMemberInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberInfoResp.ProtoReflect.Descriptor instead.
func (*GroupMemberInfoResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{40}
}

func (x *GroupMemberInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupMemberInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GroupMemberInfoResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GroupMemberInfoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupMemberInfoResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMemberInfoResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GroupMemberInfoResp) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

// 单条群组邀请/申请信息
type GroupInviteItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId         string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName       string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	InviterUid      string                 `protobuf:"bytes,4,opt,name=inviter_uid,json=inviterUid,proto3" json:"inviter_uid,omitempty"` // 邀请人
	InviteeUid      string                 `protobuf:"bytes,5,opt,name=invitee_uid,json=inviteeUid,proto3" json:"invitee_uid,omitempty"` // 被邀请人
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                           // pending, accepted, rejected
	CreatedAt       string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	InviterUsername string                 `protobuf:"bytes,8,opt,name=inviter_username,json=inviterUsername,proto3" json:"inviter_username,omitempty"`
	InviteeUsername string                 `protobuf:"bytes,9,opt,name=invitee_username,json=inviteeUsername,proto3" json:"invitee_username,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupInviteItem) Reset() {
	*x = GroupInviteItem{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInviteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInviteItem) ProtoMessage() {}

func (x *GroupInviteItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInviteItem.ProtoReflect.Descriptor instead.
func (*GroupInviteItem) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{41}
}

func (x *GroupInviteItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupInviteItem) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInviteItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInviteItem) GetInviterUid() string {
	if x != nil {
		return x.InviterUid
	}
	return ""
}

func (x *GroupInviteItem) GetInviteeUid() string {
	if x != nil {
		return x.InviteeUid
	}
	return ""
}

func (x *GroupInviteItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GroupInviteItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GroupInviteItem) GetInviterUsername() string {
	if x != nil {
		return x.InviterUsername
	}
	return ""
}

func (x *GroupInviteItem) GetInviteeUsername() string {
	if x != nil {
		return x.InviteeUsername
	}
	return ""
}

// 获取待处理群组邀请/申请列表请求
type GroupInviteListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"` // 当前用户的UID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInviteListReq) Reset() {
	*x = GroupInviteListReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInviteListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInviteListReq) ProtoMessage() {}

func (x *GroupInviteListReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInviteListReq.ProtoReflect.Descriptor instead.
func (*GroupInviteListReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{42}
}

func (x *GroupInviteListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GroupInviteListReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取待处理群组邀请/申请列表响应
type GroupInviteListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Items         []*GroupInviteItem     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInviteListResp) Reset() {
	*x = GroupInviteListResp{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInviteListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInviteListResp) ProtoMessage() {}

func (x *GroupInviteListResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInviteListResp.ProtoReflect.Descriptor instead.
func (*GroupInviteListResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{43}
}

func (x *GroupInviteListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupInviteListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GroupInviteListResp) GetItems() []*GroupInviteItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 处理群组邀请/申请请求
type HandleGroupInviteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 邀请记录的ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                             // 操作者的token
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`                        // true为同意, false为拒绝
	GroupId       string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`          // 群组ID
	InviteeUid    string                 `protobuf:"bytes,5,opt,name=invitee_uid,json=inviteeUid,proto3" json:"invitee_uid,omitempty"` // 被邀请人UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleGroupInviteReq) Reset() {
	*x = HandleGroupInviteReq{}
	mi := &file_core_protocol_proto_group_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGroupInviteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGroupInviteReq) ProtoMessage() {}

func (x *HandleGroupInviteReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_proto_group_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGroupInviteReq.ProtoReflect.Descriptor instead.
func (*HandleGroupInviteReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_proto_group_proto_rawDescGZIP(), []int{44}
}

func (x *HandleGroupInviteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HandleGroupInviteReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HandleGroupInviteReq) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *HandleGroupInviteReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *HandleGroupInviteReq) GetInviteeUid() string {
	if x != nil {
		return x.InviteeUid
	}
	return ""
}

var File_core_protocol_proto_group_proto protoreflect.FileDescriptor

const file_core_protocol_proto_group_proto_rawDesc = "" +
	"\n" +
	"\x1fcore/protocol/proto/group.proto\x12\x02pb\"\xec\x01\n" +
	"\x05Group\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\towner_uid\x18\x04 \x01(\tR\bownerUid\x12\x1f\n" +
	"\vmember_uids\x18\x05 \x03(\tR\n" +
	"memberUids\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\"\x88\x01\n" +
	"\vGroupMember\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tjoin_time\x18\x05 \x01(\x03R\bjoinTime\"\xe3\x01\n" +
	"\fGroupMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x19\n" +
	"\bfrom_uid\x18\x03 \x01(\tR\afromUid\x12#\n" +
	"\rfrom_username\x18\x04 \x01(\tR\ffromUsername\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x06 \x01(\tR\vmessageType\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\x84\x01\n" +
	"\x0eCreateGroupReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\towner_uid\x18\x03 \x01(\tR\bownerUid\x12\x1f\n" +
	"\vmember_uids\x18\x04 \x03(\tR\n" +
	"memberUids\"R\n" +
	"\x0fCreateGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\";\n" +
	"\fJoinGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"5\n" +
	"\rJoinGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"<\n" +
	"\rLeaveGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"6\n" +
	"\x0eLeaveGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\" \n" +
	"\fGroupListReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"X\n" +
	"\rGroupListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\x06groups\x18\x03 \x03(\v2\t.pb.GroupR\x06groups\",\n" +
	"\x0fGroupMembersReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"c\n" +
	"\x10GroupMembersResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\amembers\x18\x03 \x03(\v2\x0f.pb.GroupMemberR\amembers\")\n" +
	"\fGroupInfoReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"V\n" +
	"\rGroupInfoResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\x05group\x18\x03 \x01(\v2\t.pb.GroupR\x05group\"\x88\x01\n" +
	"\x13SendGroupMessageReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x19\n" +
	"\bfrom_uid\x18\x02 \x01(\tR\afromUid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\"[\n" +
	"\x14SendGroupMessageResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"t\n" +
	"\x16GroupMessageHistoryReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12)\n" +
	"\x10before_timestamp\x18\x03 \x01(\x03R\x0fbeforeTimestamp\"m\n" +
	"\x17GroupMessageHistoryResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12,\n" +
	"\bmessages\x18\x03 \x03(\v2\x10.pb.GroupMessageR\bmessages\"q\n" +
	"\x10InviteToGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\vinviter_uid\x18\x02 \x01(\tR\n" +
	"inviterUid\x12!\n" +
	"\finvitee_uids\x18\x03 \x03(\tR\vinviteeUids\"9\n" +
	"\x11InviteToGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"o\n" +
	"\x10KickFromGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\tR\voperatorUid\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x03 \x01(\tR\ttargetUid\"9\n" +
	"\x11KickFromGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"^\n" +
	"\x13SetGroupNicknameReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"<\n" +
	"\x14SetGroupNicknameResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"m\n" +
	"\x12UpdateGroupNameReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\tR\voperatorUid\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\";\n" +
	"\x13UpdateGroupNameResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"X\n" +
	"\x11SetGroupRemarkReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\":\n" +
	"\x12SetGroupRemarkResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"O\n" +
	"\x0eSetGroupDNDReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x10\n" +
	"\x03dnd\x18\x03 \x01(\bR\x03dnd\"7\n" +
	"\x0fSetGroupDNDResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x82\x01\n" +
	"\x0fSetGroupMuteReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\tR\voperatorUid\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x03 \x01(\tR\ttargetUid\x12\x12\n" +
	"\x04mute\x18\x04 \x01(\bR\x04mute\"8\n" +
	"\x10SetGroupMuteResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x8c\x01\n" +
	"\x10SetGroupAdminReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\tR\voperatorUid\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x03 \x01(\tR\ttargetUid\x12\x1b\n" +
	"\tset_admin\x18\x04 \x01(\bR\bsetAdmin\"9\n" +
	"\x11SetGroupAdminResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"O\n" +
	"\x0fDismissGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\tR\voperatorUid\"8\n" +
	"\x10DismissGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"A\n" +
	"\x12GroupMemberRoleReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"O\n" +
	"\x13GroupMemberRoleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"A\n" +
	"\x12GroupMemberInfoReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"\xb6\x01\n" +
	"\x13GroupMemberInfoResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x1b\n" +
	"\tjoin_time\x18\a \x01(\x03R\bjoinTime\"\xaa\x02\n" +
	"\x0fGroupInviteItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tR\tgroupName\x12\x1f\n" +
	"\vinviter_uid\x18\x04 \x01(\tR\n" +
	"inviterUid\x12\x1f\n" +
	"\vinvitee_uid\x18\x05 \x01(\tR\n" +
	"inviteeUid\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12)\n" +
	"\x10inviter_username\x18\b \x01(\tR\x0finviterUsername\x12)\n" +
	"\x10invitee_username\x18\t \x01(\tR\x0finviteeUsername\"<\n" +
	"\x12GroupInviteListReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"f\n" +
	"\x13GroupInviteListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\x05items\x18\x03 \x03(\v2\x13.pb.GroupInviteItemR\x05items\"\x92\x01\n" +
	"\x14HandleGroupInviteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x12\x1f\n" +
	"\vinvitee_uid\x18\x05 \x01(\tR\n" +
	"inviteeUidB\x15Z\x13im/core/protocol/pbb\x06proto3"

var (
	file_core_protocol_proto_group_proto_rawDescOnce sync.Once
	file_core_protocol_proto_group_proto_rawDescData []byte
)

func file_core_protocol_proto_group_proto_rawDescGZIP() []byte {
	file_core_protocol_proto_group_proto_rawDescOnce.Do(func() {
		file_core_protocol_proto_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_protocol_proto_group_proto_rawDesc), len(file_core_protocol_proto_group_proto_rawDesc)))
	})
	return file_core_protocol_proto_group_proto_rawDescData
}

var file_core_protocol_proto_group_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_core_protocol_proto_group_proto_goTypes = []any{
	(*Group)(nil),                   // 0: pb.Group
	(*GroupMember)(nil),             // 1: pb.GroupMember
	(*GroupMessage)(nil),            // 2: pb.GroupMessage
	(*CreateGroupReq)(nil),          // 3: pb.CreateGroupReq
	(*CreateGroupResp)(nil),         // 4: pb.CreateGroupResp
	(*JoinGroupReq)(nil),            // 5: pb.JoinGroupReq
	(*JoinGroupResp)(nil),           // 6: pb.JoinGroupResp
	(*LeaveGroupReq)(nil),           // 7: pb.LeaveGroupReq
	(*LeaveGroupResp)(nil),          // 8: pb.LeaveGroupResp
	(*GroupListReq)(nil),            // 9: pb.GroupListReq
	(*GroupListResp)(nil),           // 10: pb.GroupListResp
	(*GroupMembersReq)(nil),         // 11: pb.GroupMembersReq
	(*GroupMembersResp)(nil),        // 12: pb.GroupMembersResp
	(*GroupInfoReq)(nil),            // 13: pb.GroupInfoReq
	(*GroupInfoResp)(nil),           // 14: pb.GroupInfoResp
	(*SendGroupMessageReq)(nil),     // 15: pb.SendGroupMessageReq
	(*SendGroupMessageResp)(nil),    // 16: pb.SendGroupMessageResp
	(*GroupMessageHistoryReq)(nil),  // 17: pb.GroupMessageHistoryReq
	(*GroupMessageHistoryResp)(nil), // 18: pb.GroupMessageHistoryResp
	(*InviteToGroupReq)(nil),        // 19: pb.InviteToGroupReq
	(*InviteToGroupResp)(nil),       // 20: pb.InviteToGroupResp
	(*KickFromGroupReq)(nil),        // 21: pb.KickFromGroupReq
	(*KickFromGroupResp)(nil),       // 22: pb.KickFromGroupResp
	(*SetGroupNicknameReq)(nil),     // 23: pb.SetGroupNicknameReq
	(*SetGroupNicknameResp)(nil),    // 24: pb.SetGroupNicknameResp
	(*UpdateGroupNameReq)(nil),      // 25: pb.UpdateGroupNameReq
	(*UpdateGroupNameResp)(nil),     // 26: pb.UpdateGroupNameResp
	(*SetGroupRemarkReq)(nil),       // 27: pb.SetGroupRemarkReq
	(*SetGroupRemarkResp)(nil),      // 28: pb.SetGroupRemarkResp
	(*SetGroupDNDReq)(nil),          // 29: pb.SetGroupDNDReq
	(*SetGroupDNDResp)(nil),         // 30: pb.SetGroupDNDResp
	(*SetGroupMuteReq)(nil),         // 31: pb.SetGroupMuteReq
	(*SetGroupMuteResp)(nil),        // 32: pb.SetGroupMuteResp
	(*SetGroupAdminReq)(nil),        // 33: pb.SetGroupAdminReq
	(*SetGroupAdminResp)(nil),       // 34: pb.SetGroupAdminResp
	(*DismissGroupReq)(nil),         // 35: pb.DismissGroupReq
	(*DismissGroupResp)(nil),        // 36: pb.DismissGroupResp
	(*GroupMemberRoleReq)(nil),      // 37: pb.GroupMemberRoleReq
	(*GroupMemberRoleResp)(nil),     // 38: pb.GroupMemberRoleResp
	(*GroupMemberInfoReq)(nil),      // 39: pb.GroupMemberInfoReq
	(*GroupMemberInfoResp)(nil),     // 40: pb.GroupMemberInfoResp
	(*GroupInviteItem)(nil),         // 41: pb.GroupInviteItem
	(*GroupInviteListReq)(nil),      // 42: pb.GroupInviteListReq
	(*GroupInviteListResp)(nil),     // 43: pb.GroupInviteListResp
	(*HandleGroupInviteReq)(nil),    // 44: pb.HandleGroupInviteReq
}
var file_core_protocol_proto_group_proto_depIdxs = []int32{
	0,  // 0: pb.GroupListResp.groups:type_name -> pb.Group
	1,  // 1: pb.GroupMembersResp.members:type_name -> pb.GroupMember
	0,  // 2: pb.GroupInfoResp.group:type_name -> pb.Group
	2,  // 3: pb.GroupMessageHistoryResp.messages:type_name -> pb.GroupMessage
	41, // 4: pb.GroupInviteListResp.items:type_name -> pb.GroupInviteItem
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_core_protocol_proto_group_proto_init() }
func file_core_protocol_proto_group_proto_init() {
	if File_core_protocol_proto_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_protocol_proto_group_proto_rawDesc), len(file_core_protocol_proto_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_protocol_proto_group_proto_goTypes,
		DependencyIndexes: file_core_protocol_proto_group_proto_depIdxs,
		MessageInfos:      file_core_protocol_proto_group_proto_msgTypes,
	}.Build()
	File_core_protocol_proto_group_proto = out.File
	file_core_protocol_proto_group_proto_goTypes = nil
	file_core_protocol_proto_group_proto_depIdxs = nil
}
