// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IMMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // 消息类型: text, emoji, image, file, etc.
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"` // 发送方UID
	FromUsername  string                 `protobuf:"bytes,3,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`                              // 接收方UID
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                    // 文本内容、表情代码、图片URL、文件URL等
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // 消息时间戳
	Extra         string                 `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`                        // 扩展字段（如图片缩略图、文件名、文件大小等）
	Token         string                 `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`                        // 登录鉴权token
	Data          []byte                 `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`                          // 二进制数据（图片、文件等）
	Filename      string                 `protobuf:"bytes,10,opt,name=filename,proto3" json:"filename,omitempty"`                 // 文件名
	Filesize      int64                  `protobuf:"varint,11,opt,name=filesize,proto3" json:"filesize,omitempty"`                // 文件大小（字节）
	MimeType      string                 `protobuf:"bytes,12,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"` // MIME类型
	GroupId       string                 `protobuf:"bytes,13,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`    // 新增：群组ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMMessage) Reset() {
	*x = IMMessage{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMessage) ProtoMessage() {}

func (x *IMMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMessage.ProtoReflect.Descriptor instead.
func (*IMMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *IMMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IMMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *IMMessage) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

func (x *IMMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *IMMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IMMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IMMessage) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *IMMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IMMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *IMMessage) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *IMMessage) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *IMMessage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *IMMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// 通用通知消息（兼容好友、群组、系统等所有场景）
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                     // 通知类型，如 friend_request, group_kicked, group_dismissed, group_message
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`                                     // 触发方UID
	FromUsername  string                 `protobuf:"bytes,3,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"` // 触发方用户名
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`                                         // 接收方UID（可选，群通知可为空）
	GroupId       string                 `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                // 群ID（可选）
	GroupName     string                 `protobuf:"bytes,6,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`          // 群名（可选）
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`                               // 通知内容（如验证消息、群聊消息文本等）
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // 通知时间
	Extra         string                 `protobuf:"bytes,9,opt,name=extra,proto3" json:"extra,omitempty"`                                   // 扩展字段（结构化key:value,逗号分隔，便于未来扩展）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Notification) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

func (x *Notification) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Notification) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Notification) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Notification) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

// 文件信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                             // 服务器文件名
	OriginalName  string                 `protobuf:"bytes,2,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"` // 原始文件名
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                                    // 文件大小
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                     // 文件类型
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                       // 文件URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInfo) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type IMMessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*IMMessage           `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMMessageList) Reset() {
	*x = IMMessageList{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMessageList) ProtoMessage() {}

func (x *IMMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMessageList.ProtoReflect.Descriptor instead.
func (*IMMessageList) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *IMMessageList) GetMessages() []*IMMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type APIResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResp) Reset() {
	*x = APIResp{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResp) ProtoMessage() {}

func (x *APIResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResp.ProtoReflect.Descriptor instead.
func (*APIResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *APIResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *APIResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *APIResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取最近私聊消息
type GetRecentPrivateMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentPrivateMessagesReq) Reset() {
	*x = GetRecentPrivateMessagesReq{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentPrivateMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentPrivateMessagesReq) ProtoMessage() {}

func (x *GetRecentPrivateMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentPrivateMessagesReq.ProtoReflect.Descriptor instead.
func (*GetRecentPrivateMessagesReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecentPrivateMessagesReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetRecentPrivateMessagesReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GetRecentPrivateMessagesReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取最近群聊消息
type GetRecentGroupMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentGroupMessagesReq) Reset() {
	*x = GetRecentGroupMessagesReq{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentGroupMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentGroupMessagesReq) ProtoMessage() {}

func (x *GetRecentGroupMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentGroupMessagesReq.ProtoReflect.Descriptor instead.
func (*GetRecentGroupMessagesReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecentGroupMessagesReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetRecentGroupMessagesReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\bprotocol\"\xd0\x02\n" +
	"\tIMMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12#\n" +
	"\rfrom_username\x18\x03 \x01(\tR\ffromUsername\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05extra\x18\a \x01(\tR\x05extra\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\n" +
	" \x01(\tR\bfilename\x12\x1a\n" +
	"\bfilesize\x18\v \x01(\x03R\bfilesize\x12\x1b\n" +
	"\tmime_type\x18\f \x01(\tR\bmimeType\x12\x19\n" +
	"\bgroup_id\x18\r \x01(\tR\agroupId\"\xf3\x01\n" +
	"\fNotification\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12#\n" +
	"\rfrom_username\x18\x03 \x01(\tR\ffromUsername\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x06 \x01(\tR\tgroupName\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05extra\x18\t \x01(\tR\x05extra\"\x85\x01\n" +
	"\bFileInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12#\n" +
	"\roriginal_name\x18\x02 \x01(\tR\foriginalName\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"@\n" +
	"\rIMMessageList\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.protocol.IMMessageR\bmessages\"C\n" +
	"\aAPIResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"W\n" +
	"\x1bGetRecentPrivateMessagesReq\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"L\n" +
	"\x19GetRecentGroupMessagesReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05countB\x18Z\x16im/core/protocol/pb;pbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_proto_goTypes = []any{
	(*IMMessage)(nil),                   // 0: protocol.IMMessage
	(*Notification)(nil),                // 1: protocol.Notification
	(*FileInfo)(nil),                    // 2: protocol.FileInfo
	(*IMMessageList)(nil),               // 3: protocol.IMMessageList
	(*APIResp)(nil),                     // 4: protocol.APIResp
	(*GetRecentPrivateMessagesReq)(nil), // 5: protocol.GetRecentPrivateMessagesReq
	(*GetRecentGroupMessagesReq)(nil),   // 6: protocol.GetRecentGroupMessagesReq
}
var file_message_proto_depIdxs = []int32{
	0, // 0: protocol.IMMessageList.messages:type_name -> protocol.IMMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
