// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/protocol/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IMMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`            // 消息类型: text, image, etc.
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`            // 发送方UID
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`                // 接收方UID
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`      // 文本内容或图片URL等
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 消息时间戳
	Extra         string                 `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`          // 扩展字段（如图片缩略图、文件名等）
	Token         string                 `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`          // 登录鉴权token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMMessage) Reset() {
	*x = IMMessage{}
	mi := &file_core_protocol_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMMessage) ProtoMessage() {}

func (x *IMMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMMessage.ProtoReflect.Descriptor instead.
func (*IMMessage) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{0}
}

func (x *IMMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IMMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *IMMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *IMMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IMMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IMMessage) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *IMMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type APIResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResp) Reset() {
	*x = APIResp{}
	mi := &file_core_protocol_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResp) ProtoMessage() {}

func (x *APIResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResp.ProtoReflect.Descriptor instead.
func (*APIResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{1}
}

func (x *APIResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *APIResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *APIResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_core_protocol_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_core_protocol_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPwdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	NewPwd        string                 `protobuf:"bytes,2,opt,name=new_pwd,json=newPwd,proto3" json:"new_pwd,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPwdReq) Reset() {
	*x = ResetPwdReq{}
	mi := &file_core_protocol_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPwdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPwdReq) ProtoMessage() {}

func (x *ResetPwdReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPwdReq.ProtoReflect.Descriptor instead.
func (*ResetPwdReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{4}
}

func (x *ResetPwdReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPwdReq) GetNewPwd() string {
	if x != nil {
		return x.NewPwd
	}
	return ""
}

func (x *ResetPwdReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateUsernameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NewUsername   string                 `protobuf:"bytes,2,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameReq) Reset() {
	*x = UpdateUsernameReq{}
	mi := &file_core_protocol_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameReq) ProtoMessage() {}

func (x *UpdateUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameReq.ProtoReflect.Descriptor instead.
func (*UpdateUsernameReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUsernameReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdateUsernameReq) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

type UpdatePwdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	OldPwd        string                 `protobuf:"bytes,2,opt,name=old_pwd,json=oldPwd,proto3" json:"old_pwd,omitempty"`
	NewPwd        string                 `protobuf:"bytes,3,opt,name=new_pwd,json=newPwd,proto3" json:"new_pwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePwdReq) Reset() {
	*x = UpdatePwdReq{}
	mi := &file_core_protocol_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePwdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePwdReq) ProtoMessage() {}

func (x *UpdatePwdReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePwdReq.ProtoReflect.Descriptor instead.
func (*UpdatePwdReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePwdReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdatePwdReq) GetOldPwd() string {
	if x != nil {
		return x.OldPwd
	}
	return ""
}

func (x *UpdatePwdReq) GetNewPwd() string {
	if x != nil {
		return x.NewPwd
	}
	return ""
}

type TokenCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCheckReq) Reset() {
	*x = TokenCheckReq{}
	mi := &file_core_protocol_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCheckReq) ProtoMessage() {}

func (x *TokenCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCheckReq.ProtoReflect.Descriptor instead.
func (*TokenCheckReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{7}
}

func (x *TokenCheckReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeleteAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountReq) Reset() {
	*x = DeleteAccountReq{}
	mi := &file_core_protocol_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountReq) ProtoMessage() {}

func (x *DeleteAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountReq.ProtoReflect.Descriptor instead.
func (*DeleteAccountReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAccountReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_core_protocol_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{9}
}

func (x *UserInfoReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_core_protocol_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SendEmailCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailCodeReq) Reset() {
	*x = SendEmailCodeReq{}
	mi := &file_core_protocol_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailCodeReq) ProtoMessage() {}

func (x *SendEmailCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailCodeReq.ProtoReflect.Descriptor instead.
func (*SendEmailCodeReq) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{11}
}

func (x *SendEmailCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 通知消息
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`            // 通知类型，如 friend_request
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`            // 触发方UID
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`                // 接收方UID
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`      // 通知内容（如验证消息）
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 通知时间
	Extra         string                 `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`          // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_core_protocol_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_core_protocol_message_proto_rawDescGZIP(), []int{12}
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Notification) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Notification) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

var File_core_protocol_message_proto protoreflect.FileDescriptor

const file_core_protocol_message_proto_rawDesc = "" +
	"\n" +
	"\x1bcore/protocol/message.proto\x12\bprotocol\"\xa7\x01\n" +
	"\tIMMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\tR\x05extra\x12\x14\n" +
	"\x05token\x18\a \x01(\tR\x05token\"C\n" +
	"\aAPIResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"[\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"8\n" +
	"\bLoginReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\vResetPwdReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x17\n" +
	"\anew_pwd\x18\x02 \x01(\tR\x06newPwd\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"H\n" +
	"\x11UpdateUsernameReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12!\n" +
	"\fnew_username\x18\x02 \x01(\tR\vnewUsername\"R\n" +
	"\fUpdatePwdReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x17\n" +
	"\aold_pwd\x18\x02 \x01(\tR\x06oldPwd\x12\x17\n" +
	"\anew_pwd\x18\x03 \x01(\tR\x06newPwd\"%\n" +
	"\rTokenCheckReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"$\n" +
	"\x10DeleteAccountReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"#\n" +
	"\vUserInfoReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"!\n" +
	"\tLogoutReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"(\n" +
	"\x10SendEmailCodeReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x94\x01\n" +
	"\fNotification\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\tR\x05extraB\x18Z\x16im/core/protocol/pb;pbb\x06proto3"

var (
	file_core_protocol_message_proto_rawDescOnce sync.Once
	file_core_protocol_message_proto_rawDescData []byte
)

func file_core_protocol_message_proto_rawDescGZIP() []byte {
	file_core_protocol_message_proto_rawDescOnce.Do(func() {
		file_core_protocol_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_protocol_message_proto_rawDesc), len(file_core_protocol_message_proto_rawDesc)))
	})
	return file_core_protocol_message_proto_rawDescData
}

var file_core_protocol_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_core_protocol_message_proto_goTypes = []any{
	(*IMMessage)(nil),         // 0: protocol.IMMessage
	(*APIResp)(nil),           // 1: protocol.APIResp
	(*RegisterReq)(nil),       // 2: protocol.RegisterReq
	(*LoginReq)(nil),          // 3: protocol.LoginReq
	(*ResetPwdReq)(nil),       // 4: protocol.ResetPwdReq
	(*UpdateUsernameReq)(nil), // 5: protocol.UpdateUsernameReq
	(*UpdatePwdReq)(nil),      // 6: protocol.UpdatePwdReq
	(*TokenCheckReq)(nil),     // 7: protocol.TokenCheckReq
	(*DeleteAccountReq)(nil),  // 8: protocol.DeleteAccountReq
	(*UserInfoReq)(nil),       // 9: protocol.UserInfoReq
	(*LogoutReq)(nil),         // 10: protocol.LogoutReq
	(*SendEmailCodeReq)(nil),  // 11: protocol.SendEmailCodeReq
	(*Notification)(nil),      // 12: protocol.Notification
}
var file_core_protocol_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_protocol_message_proto_init() }
func file_core_protocol_message_proto_init() {
	if File_core_protocol_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_protocol_message_proto_rawDesc), len(file_core_protocol_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_protocol_message_proto_goTypes,
		DependencyIndexes: file_core_protocol_message_proto_depIdxs,
		MessageInfos:      file_core_protocol_message_proto_msgTypes,
	}.Build()
	File_core_protocol_message_proto = out.File
	file_core_protocol_message_proto_goTypes = nil
	file_core_protocol_message_proto_depIdxs = nil
}
