// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/protocol/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户信息响应
type UserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResp) Reset() {
	*x = UserInfoResp{}
	mi := &file_core_protocol_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResp) ProtoMessage() {}

func (x *UserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResp.ProtoReflect.Descriptor instead.
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return file_core_protocol_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserInfoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfoResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_core_protocol_user_proto protoreflect.FileDescriptor

const file_core_protocol_user_proto_rawDesc = "" +
	"\n" +
	"\x18core/protocol/user.proto\x12\bprotocol\"x\n" +
	"\fUserInfoResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msgB\x18Z\x16im/core/protocol/pb;pbb\x06proto3"

var (
	file_core_protocol_user_proto_rawDescOnce sync.Once
	file_core_protocol_user_proto_rawDescData []byte
)

func file_core_protocol_user_proto_rawDescGZIP() []byte {
	file_core_protocol_user_proto_rawDescOnce.Do(func() {
		file_core_protocol_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_protocol_user_proto_rawDesc), len(file_core_protocol_user_proto_rawDesc)))
	})
	return file_core_protocol_user_proto_rawDescData
}

var file_core_protocol_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_protocol_user_proto_goTypes = []any{
	(*UserInfoResp)(nil), // 0: protocol.UserInfoResp
}
var file_core_protocol_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_protocol_user_proto_init() }
func file_core_protocol_user_proto_init() {
	if File_core_protocol_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_protocol_user_proto_rawDesc), len(file_core_protocol_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_protocol_user_proto_goTypes,
		DependencyIndexes: file_core_protocol_user_proto_depIdxs,
		MessageInfos:      file_core_protocol_user_proto_msgTypes,
	}.Build()
	File_core_protocol_user_proto = out.File
	file_core_protocol_user_proto_goTypes = nil
	file_core_protocol_user_proto_depIdxs = nil
}
